### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by deeplearn-art** [SHI-Labs/Text2Video-Zero-sd-webui#2]
Could be a problem with my setup, but haven't encountered anything like it with other sd-webui extensions

```
Installing requirements for Web UI



Error running install.py for extension extensions\Text2Video-Zero-sd-webui.
Command: "C:\stable-diffusion-webui\venv\Scripts\python.exe" "extensions\Text2Video-Zero-sd-webui\install.py"
Error code: 1
stdout: Installing requirements for Text2Video-Zero

stderr: Traceback (most recent call last):
  File "C:\stable-diffusion-webui\extensions\Text2Video-Zero-sd-webui\install.py", line 28, in <module>
    launch.run_pip(f"install -r \"{os.path.join(ext_dir, 'requirements.txt')}\"", "requirements for Text2Video-Zero")
  File "C:\stable-diffusion-webui\launch.py", line 145, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "C:\stable-diffusion-webui\launch.py", line 113, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for Text2Video-Zero.
Command: "C:\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install -r "C:\stable-diffusion-webui\extensions\Text2Video-Zero-sd-webui\requirements.txt" --prefer-binary
Error code: 1
stdout: Collecting accelerate==0.16.0
  Using cached accelerate-0.16.0-py3-none-any.whl (199 kB)
Requirement already satisfied: addict==2.4.0 in c:\stable-diffusion-webui\venv\lib\site-packages (from -r C:\stable-diffusion-webui\extensions\Text2Video-Zero-sd-webui\requirements.txt (line 2)) (2.4.0)
Collecting albumentations==1.3.0
  Using cached albumentations-1.3.0-py3-none-any.whl (123 kB)
Requirement already satisfied: basicsr==1.4.2 in c:\stable-diffusion-webui\venv\lib\site-packages (from -r C:\stable-diffusion-webui\extensions\Text2Video-Zero-sd-webui\requirements.txt (line 4)) (1.4.2)
Collecting decord==0.6.0
  Using cached decord-0.6.0-py3-none-win_amd64.whl (24.7 MB)
Collecting diffusers==0.14.0
  Using cached diffusers-0.14.0-py3-none-any.whl (737 kB)
Collecting einops==0.6.0
  Using cached einops-0.6.0-py3-none-any.whl (41 kB)
Collecting gradio==3.23.0
  Using cached gradio-3.23.0-py3-none-any.whl (15.8 MB)
Collecting kornia==0.6
  Using cached kornia-0.6.0-py2.py3-none-any.whl (367 kB)
Collecting imageio==2.9.0
  Using cached imageio-2.9.0-py3-none-any.whl (3.3 MB)
Collecting imageio-ffmpeg==0.4.2
  Using cached imageio_ffmpeg-0.4.2-py3-none-win_amd64.whl (22.6 MB)
Collecting invisible-watermark>=0.1.5
  Using cached invisible_watermark-0.1.5-py3-none-any.whl (1.6 MB)
Collecting moviepy==1.0.3
  Using cached moviepy-1.0.3.tar.gz (388 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting numpy==1.24.1
  Using cached numpy-1.24.1-cp310-cp310-win_amd64.whl (14.8 MB)
Collecting omegaconf==2.3.0
  Using cached omegaconf-2.3.0-py3-none-any.whl (79 kB)
Collecting open_clip_torch==2.16.0
  Using cached open_clip_torch-2.16.0-py3-none-any.whl (1.5 MB)
Collecting opencv_python==4.5.1.48
  Using cached opencv-python-4.5.1.48.tar.gz (88.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'

stderr:   error: subprocess-exited-with-error

  pip subprocess to install build dependencies did not run successfully.
  exit code: 1

  [236 lines of output]
  Ignoring numpy: markers 'python_version == "3.6" and platform_machine != "aarch64"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.6" and sys_platform == "linux" and platform_machine == "aarch64"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_machine != "aarch64"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.8" and platform_machine != "aarch64"' don't match your environment
  Collecting setuptools
    Using cached setuptools-67.6.1-py3-none-any.whl (1.1 MB)
  Collecting wheel
    Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
  Collecting scikit-build
    Using cached scikit_build-0.16.7-py3-none-any.whl (79 kB)
  Collecting cmake
    Using cached cmake-3.26.1-py2.py3-none-win_amd64.whl (33.0 MB)
  Collecting pip
    Using cached pip-23.0.1-py3-none-any.whl (2.1 MB)
  Collecting numpy==1.19.3
    Using cached numpy-1.19.3.zip (7.3 MB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'error'
    error: subprocess-exited-with-error

    Preparing metadata (pyproject.toml) did not run successfully.
    exit code: 1

    [194 lines of output]
    setup.py:67: RuntimeWarning: NumPy 1.19.3 may not yet support Python 3.10.
      warnings.warn(
    Running from numpy source directory.
    setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    Processing numpy/random\_bounded_integers.pxd.in
    Processing numpy/random\bit_generator.pyx
    Processing numpy/random\mtrand.pyx
    Processing numpy/random\_bounded_integers.pyx.in
    Processing numpy/random\_common.pyx
    Processing numpy/random\_generator.pyx
    Processing numpy/random\_mt19937.pyx
    Processing numpy/random\_pcg64.pyx
    Processing numpy/random\_philox.pyx
    Processing numpy/random\_sfc64.pyx
    Cythonizing sources
    blas_opt_info:
    blas_mkl_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries mkl_rt not found in ['C:\\stable-diffusion-webui\\venv\\lib', 'C:\\']
      NOT AVAILABLE

    blis_info:
      libraries blis not found in ['C:\\stable-diffusion-webui\\venv\\lib', 'C:\\']
      NOT AVAILABLE

    openblas_info:
      libraries openblas not found in ['C:\\stable-diffusion-webui\\venv\\lib', 'C:\\']
    get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
    customize GnuFCompiler
    Could not locate executable g77
    Could not locate executable f77
    customize IntelVisualFCompiler
    Could not locate executable ifort
    Could not locate executable ifl
    customize AbsoftFCompiler
    Could not locate executable f90
    customize CompaqVisualFCompiler
    Could not locate executable DF
    customize IntelItaniumVisualFCompiler
    Could not locate executable efl
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize G95FCompiler
    Could not locate executable g95
    customize IntelEM64VisualFCompiler
    customize IntelEM64TFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize PGroupFlangCompiler
    Could not locate executable flang
    don't know how to compile Fortran code on platform 'nt'
      NOT AVAILABLE

    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas not found in ['C:\\stable-diffusion-webui\\venv\\lib', 'C:\\']
      NOT AVAILABLE

    atlas_3_10_blas_info:
      libraries satlas not found in ['C:\\stable-diffusion-webui\\venv\\lib', 'C:\\']
      NOT AVAILABLE

    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in ['C:\\stable-diffusion-webui\\venv\\lib', 'C:\\']
      NOT AVAILABLE

    atlas_blas_info:
      libraries f77blas,cblas,atlas not found in ['C:\\stable-diffusion-webui\\venv\\lib', 'C:\\']
      NOT AVAILABLE

    accelerate_info:
      NOT AVAILABLE

    C:\Users\jle\AppData\Local\Temp\pip-install-vlnhi3_o\numpy_839d32a6c8924de58cc2ce4c2ffe7d39\numpy\distutils\system_info.py:1914: UserWarning:
        Optimized (vendor) Blas libraries are not found.
        Falls back to netlib Blas library which has worse performance.
        A better performance should be easily gained by switching
        Blas library.
      if self._calc_info(blas):
    blas_info:
      libraries blas not found in ['C:\\stable-diffusion-webui\\venv\\lib', 'C:\\']
      NOT AVAILABLE

    C:\Users\jle\AppData\Local\Temp\pip-install-vlnhi3_o\numpy_839d32a6c8924de58cc2ce4c2ffe7d39\numpy\distutils\system_info.py:1914: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      if self._calc_info(blas):
    blas_src_info:
      NOT AVAILABLE

    C:\Users\jle\AppData\Local\Temp\pip-install-vlnhi3_o\numpy_839d32a6c8924de58cc2ce4c2ffe7d39\numpy\distutils\system_info.py:1914: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      if self._calc_info(blas):
      NOT AVAILABLE

    non-existing path in 'numpy\\distutils': 'site.cfg'
    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['C:\\stable-diffusion-webui\\venv\\lib', 'C:\\']
      NOT AVAILABLE

    openblas_lapack_info:
      libraries openblas not found in ['C:\\stable-diffusion-webui\\venv\\lib', 'C:\\']
      NOT AVAILABLE

    openblas_clapack_info:
      libraries openblas,lapack not found in ['C:\\stable-diffusion-webui\\venv\\lib', 'C:\\']
      NOT AVAILABLE

    flame_info:
      libraries flame not found in ['C:\\stable-diffusion-webui\\venv\\lib', 'C:\\']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in C:\stable-diffusion-webui\venv\lib
      libraries tatlas,tatlas not found in C:\stable-diffusion-webui\venv\lib
      libraries lapack_atlas not found in C:\
      libraries tatlas,tatlas not found in C:\
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
      libraries lapack_atlas not found in C:\stable-diffusion-webui\venv\lib
      libraries satlas,satlas not found in C:\stable-diffusion-webui\venv\lib
      libraries lapack_atlas not found in C:\
      libraries satlas,satlas not found in C:\
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in C:\stable-diffusion-webui\venv\lib
      libraries ptf77blas,ptcblas,atlas not found in C:\stable-diffusion-webui\venv\lib
      libraries lapack_atlas not found in C:\
      libraries ptf77blas,ptcblas,atlas not found in C:\
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
      libraries lapack_atlas not found in C:\stable-diffusion-webui\venv\lib
      libraries f77blas,cblas,atlas not found in C:\stable-diffusion-webui\venv\lib
      libraries lapack_atlas not found in C:\
      libraries f77blas,cblas,atlas not found in C:\
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    lapack_info:
      libraries lapack not found in ['C:\\stable-diffusion-webui\\venv\\lib', 'C:\\']
      NOT AVAILABLE

    C:\Users\jle\AppData\Local\Temp\pip-install-vlnhi3_o\numpy_839d32a6c8924de58cc2ce4c2ffe7d39\numpy\distutils\system_info.py:1748: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
    lapack_src_info:
      NOT AVAILABLE

    C:\Users\jle\AppData\Local\Temp\pip-install-vlnhi3_o\numpy_839d32a6c8924de58cc2ce4c2ffe7d39\numpy\distutils\system_info.py:1748: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
      NOT AVAILABLE

    numpy_linalg_lapack_lite:
      FOUND:
        language = c
        define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]

    C:\Users\jle\AppData\Local\Temp\pip-build-env-q_78glhw\overlay\Lib\site-packages\setuptools\_distutils\dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    running dist_info
    running build_src
    build_src
    building py_modules sources
    creating build
    creating build\src.win-amd64-3.10
    creating build\src.win-amd64-3.10\numpy
    creating build\src.win-amd64-3.10\numpy\distutils
    building library "npymath" sources
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: metadata-generation-failed

  Encountered error while generating package metadata.

  See above for output.

  note: This is an issue with the package mentioned above, not pip.
  hint: See above for details.

  [notice] A new release of pip available: 22.3.1 -> 23.0.1
  [notice] To update, run: C:\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

pip subprocess to install build dependencies did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: C:\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip




Launching Web UI with arguments: --medvram --xformers
Error loading script: main.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\stable-diffusion-webui\extensions\Text2Video-Zero-sd-webui\scripts\main.py", line 5, in <module>
    from model import Model, ModelType
  File "C:\stable-diffusion-webui\extensions\Text2Video-Zero-sd-webui\model.py", line 6, in <module>
    import decord
ModuleNotFoundError: No module named 'decord'
```

**Comment by ericlormul** [comment]
seems installation of "opencv_python==4.5.1.48" failed on your system, you may try other opencv_python versions that are compatible on your machine, by modifying it in requirements.txt. Specific version of opencv_python require certain system dependencies and the version doesn't matter that much.

**Comment by djbielejeski** [comment]
I get this error as well.  This seems to fix it, even though there are other errors after this.

updated `stable-diffusion-webui\extensions\Text2Video-Zero-sd-webui\requirements.txt`

```
opencv_python==4.5.1.48
opencv-contrib-python==4.3.0.36
```

to

```
opencv-python==4.7.0.72
opencv-contrib-python==4.7.0.72
```

**Comment by mariaWitch** [comment]
I am able to get past the installing of dependencies even with failures, but the extension is still able to start. However, upon final startup, this error now pops up.
```

Traceback (most recent call last):
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\extensions\Text2Video-Zero-sd-webui\scripts\main.py", line 8, in <module>
    from app_pose import create_demo as create_demo_pose
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\extensions\Text2Video-Zero-sd-webui\app_pose.py", line 65, in <module>
    def on_video_path_update(evt: gr.EventData):
AttributeError: module 'gradio' has no attribute 'EventData'
```

**Comment by mariaWitch** [comment]
Okay I got past the previous issue, but now I am running into the following error, and it completely ruins the UI every time. Note, I am running on Low-VRAM but I have seen people fail to load this portion even with 24gb of vram. (I have 8gb, and I couldn't load it with med vram or low vram.)
```

Error executing callback ui_tabs_callback for C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\extensions\Text2Video-Zero-sd-webui\scripts\main.py
Traceback (most recent call last):
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\modules\script_callbacks.py", line 126, in ui_tabs_callback
    res += c.callback() or []
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\extensions\Text2Video-Zero-sd-webui\scripts\main.py", line 18, in on_ui_tabs
    create_demo_text_to_video(model)
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\extensions\Text2Video-Zero-sd-webui\app_text_to_video.py", line 61, in create_demo
    gr.Examples(examples=examples,
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\gradio\helpers.py", line 70, in create_examples
    utils.synchronize_async(examples_obj.create)
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 516, in synchronize_async
    return fsspec.asyn.sync(fsspec.asyn.get_loop(), func, *args, **kwargs)
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\fsspec\asyn.py", line 96, in sync
    raise return_result
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\fsspec\asyn.py", line 53, in _runner
    result[0] = await coro
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\gradio\helpers.py", line 277, in create
    await self.cache()
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\gradio\helpers.py", line 311, in cache
    prediction = await Context.root_block.process_api(
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\extensions\Text2Video-Zero-sd-webui\model.py", line 286, in process_text2video
    result = self.inference(prompt=[prompt],
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\extensions\Text2Video-Zero-sd-webui\model.py", line 100, in inference
    return self.pipe(generator=self.generator, **kwargs).videos[0]
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\extensions\Text2Video-Zero-sd-webui\text_to_video\text_to_video_pipeline.py", line 372, in __call__
    ddim_res = self.DDIM_backward(num_inference_steps=num_inference_steps, timesteps=timesteps, skip_t=t1, t0=-1, t1=-1, do_classifier_free_guidance=do_classifier_free_guidance,
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\extensions\Text2Video-Zero-sd-webui\text_to_video\text_to_video_pipeline.py", line 164, in DDIM_backward
    noise_pred = self.unet(
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 582, in forward
    sample, res_samples = downsample_block(
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 837, in forward
    hidden_states = attn(
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\transformer_2d.py", line 265, in forward
    hidden_states = block(
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\attention.py", line 291, in forward
    attn_output = self.attn1(
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\cross_attention.py", line 205, in forward
    return self.processor(
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\extensions\Text2Video-Zero-sd-webui\utils.py", line 184, in __call__
    attention_probs = attn.get_attention_scores(query, key, attention_mask)
  File "C:\Users\maria\Downloads\Architecture\NovelAI\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\cross_attention.py", line 234, in get_attention_scores
    baddbmm_input = torch.empty(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.00 GiB (GPU 0; 8.00 GiB total capacity; 2.65 GiB already allocated; 2.56 GiB free; 3.38 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
