### ISSUE TITLE
Error after generating video

### ISSUE THREAD

**Issue by djbielejeski** [SHI-Labs/Text2Video-Zero-sd-webui#3]
Error after generating video

`
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:/stable-diffusion/automatic1111-images/txt2img-images/controlnet-m2m'
`

```
Error completing request05:27, 13.51it/s]
Arguments: ('task(helfq4s6m6ne10e)', 'by mike deodato', '((deformed)), (cross-eyed), (closed eyes), (bad anatomy), disfigured, (mutation), (mutated), (extra limbs)', [], 50, 16, False, False, 1, 1, 8, -1.0, -1.0, 0, 0, 0, False, 512, 896, False, 1, 2, 'Latent', 0, 0, 0, [], 5, False, 7, 100, 'Constant', 0, 'Constant', 0, 4, False, False, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, None, 'Refresh models', <scripts.external_code.ControlNetUnit object at 0x000001FFA8C748E0>, <scripts.external_code.ControlNetUnit object at 0x00000202941259C0>, <scripts.external_code.ControlNetUnit object at 0x0000020294124A60>, False, False, 'Horizontal', '1,1', '0.2', False, False, False, 'Attention', False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 150, 0.2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, True, -1.0, True, 'Not set', 'Not set', 'Not set', 'Not set', 'No focus', 'None', False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, 'C:\\1_a_new_hope_leia_1mnmi4eyn.mp4', False, None, False, None, False, 50) {}
Traceback (most recent call last):
  File "C:\Users\David\Dev\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\David\Dev\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\David\Dev\stable-diffusion-webui\modules\txt2img.py", line 53, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "C:\Users\David\Dev\stable-diffusion-webui\modules\scripts.py", line 399, in run
    processed = script.run(p, *script_args)
  File "C:\Users\David\Dev\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\movie2movie.py", line 129, in run
    seq = images.get_next_sequence_number(f"{p.outpath_samples}{_BASEDIR}", "")
  File "C:\Users\David\Dev\stable-diffusion-webui\modules\images.py", line 446, in get_next_sequence_number
    for p in os.listdir(path):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:/stable-diffusion/automatic1111-images/txt2img-images/controlnet-m2m'
```

My Settings
![image](https://user-images.githubusercontent.com/2463282/228982994-674d0800-da74-4e04-bd9b-e2b7b5184daa.png)
![image](https://user-images.githubusercontent.com/2463282/228983040-c6931341-5934-43a4-a255-077559b489fd.png)
![image](https://user-images.githubusercontent.com/2463282/228983069-048987db-9864-45c7-8523-2ba18c076ed5.png)

**Comment by djbielejeski** [comment]
I didn't finish all the install instructions
